development:
 adapter: postgresql
 encoding: unicode
 database: action-cable-chat-app-development
 host: localhost
 pool: 5
 username: postgres
 password: interakt

test:
 adapter: postgresql
 encoding: unicode
 database: action-cable-chat-app-test
 host: localhost
 pool: 5
 username: postgres
 password: interakt