# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef7be37d6cc4004ec224a9f5a51aec65157ad6044688629bb83a99584f9ac99015d729c7d451302eb05bd7b92eec490ca9595249346a45a76a0c6e269f59f4e6

test:
  secret_key_base: 7ca7d6e04386ab6e4b3f46c547fe3202a592e4b2f62358bc0cd599f983c012c63d245e9d5c23321ceb308771d3019e25587630e115f8d2bbdbb465ec59993b08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
